{
 "title": "ESP32 Env Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "expr": "env_temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "format": "humidity",
   "valueName": "current",
   "targets": [
    { "expr": "env_humidity" }
   ]
  },
  {
   "title": "Pressure",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "format": "pressurehpa",
   "valueName": "current",
   "targets": [
    { "expr": "env_pressure" }
   ]
  },
  {
   "title": "eCO2",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "format": "ppm",
   "valueName": "current",
   "targets": [
    { "expr": "env_eco2" }
   ]
  },
  {
   "title": "TVOC",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "format": "conppb",
   "valueName": "current",
   "targets": [
    { "expr": "env_tvoc" }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "env_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "env_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "env_pressure", "legendFormat": "Pressure" }
   ]
  },
  {
   "title": "eCO2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "env_eco2", "legendFormat": "eCO2" }
   ]
  },
  {
   "title": "TVOC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    { "expr": "env_tvoc", "legendFormat": "tVOC" }
   ]
  }
 ]
}